#!/bin/bash
# reextend swaps file extentions
#
# Matthew Brower
#	10/02
# 
# Platform: Linux 4.4.0-36-generic x86_64 
# 
# EDITOR: tabstop=2, cols=80
# 
# 
#
if [ $# != 2 ]; then
	echo "2 paramaters only please"
	exit 1
fi

for f in *; do
	newFile=${f/$1/$2};
	#error checking
	#echo "$newFile";
if [ "$f" != "$newFile" ]; then
	mv "$f" "$newFile";
fi
done
